### ISSUE TITLE
meta-tensorflow/meta-demo/conf/layer.conf needs zeus compatibility added

### ISSUE THREAD

**Issue by gkenaley** [Wind-River/meta-tensorflow#4]
In File:
meta-tensorflow/meta-demo/conf/layer.conf
   Change:
LAYERSERIES_COMPAT_tensorflow-demo = "warrior"
   To:
LAYERSERIES_COMPAT_tensorflow-demo = "warrior zeus"
   Test:
Make sure the Master Branch builds with WRL LTS19.

**Comment by hongxu-jia** [comment]
Done
